2020-01-29 21:28:08,755 ERROR: Exception on /index [GET] [in /home/raymun/.local/share/virtualenvs/Proyectos-TA_eUHkL/lib/python3.5/site-packages/flask/app.py:1891]
Traceback (most recent call last):
  File "/home/raymun/.local/share/virtualenvs/Proyectos-TA_eUHkL/lib/python3.5/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/raymun/.local/share/virtualenvs/Proyectos-TA_eUHkL/lib/python3.5/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/raymun/.local/share/virtualenvs/Proyectos-TA_eUHkL/lib/python3.5/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/raymun/.local/share/virtualenvs/Proyectos-TA_eUHkL/lib/python3.5/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/raymun/.local/share/virtualenvs/Proyectos-TA_eUHkL/lib/python3.5/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/raymun/.local/share/virtualenvs/Proyectos-TA_eUHkL/lib/python3.5/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/raymun/Proyectos/WebPages/projects/personal_web_page/app/routes.py", line 23, in index
    next_url=next_url, prev_url=prev_url)
  File "/home/raymun/.local/share/virtualenvs/Proyectos-TA_eUHkL/lib/python3.5/site-packages/flask/templating.py", line 138, in render_template
    ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "/home/raymun/.local/share/virtualenvs/Proyectos-TA_eUHkL/lib/python3.5/site-packages/jinja2/environment.py", line 930, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "/home/raymun/.local/share/virtualenvs/Proyectos-TA_eUHkL/lib/python3.5/site-packages/jinja2/environment.py", line 883, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "/home/raymun/.local/share/virtualenvs/Proyectos-TA_eUHkL/lib/python3.5/site-packages/jinja2/environment.py", line 857, in _load_template
    template = self.loader.load(self, name, globals)
  File "/home/raymun/.local/share/virtualenvs/Proyectos-TA_eUHkL/lib/python3.5/site-packages/jinja2/loaders.py", line 129, in load
    code = environment.compile(source, name, filename)
  File "/home/raymun/.local/share/virtualenvs/Proyectos-TA_eUHkL/lib/python3.5/site-packages/jinja2/environment.py", line 638, in compile
    self.handle_exception(source=source_hint)
  File "/home/raymun/.local/share/virtualenvs/Proyectos-TA_eUHkL/lib/python3.5/site-packages/jinja2/environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "/home/raymun/.local/share/virtualenvs/Proyectos-TA_eUHkL/lib/python3.5/site-packages/jinja2/_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "/home/raymun/Proyectos/WebPages/projects/personal_web_page/app/templates/index.html", line 59, in template
    <p>{{ _('Collaborate with me, create teams and connect all things. Rankings, and extended premium features') }}
jinja2.exceptions.TemplateSyntaxError: expected token ',', got 'Collaborate'
2020-01-29 21:30:38,477 ERROR: Exception on /index [GET] [in /home/raymun/.local/share/virtualenvs/Proyectos-TA_eUHkL/lib/python3.5/site-packages/flask/app.py:1891]
Traceback (most recent call last):
  File "/home/raymun/.local/share/virtualenvs/Proyectos-TA_eUHkL/lib/python3.5/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/raymun/.local/share/virtualenvs/Proyectos-TA_eUHkL/lib/python3.5/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/raymun/.local/share/virtualenvs/Proyectos-TA_eUHkL/lib/python3.5/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/raymun/.local/share/virtualenvs/Proyectos-TA_eUHkL/lib/python3.5/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/raymun/.local/share/virtualenvs/Proyectos-TA_eUHkL/lib/python3.5/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/raymun/.local/share/virtualenvs/Proyectos-TA_eUHkL/lib/python3.5/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/raymun/Proyectos/WebPages/projects/personal_web_page/app/routes.py", line 23, in index
    next_url=next_url, prev_url=prev_url)
  File "/home/raymun/.local/share/virtualenvs/Proyectos-TA_eUHkL/lib/python3.5/site-packages/flask/templating.py", line 138, in render_template
    ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "/home/raymun/.local/share/virtualenvs/Proyectos-TA_eUHkL/lib/python3.5/site-packages/jinja2/environment.py", line 930, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "/home/raymun/.local/share/virtualenvs/Proyectos-TA_eUHkL/lib/python3.5/site-packages/jinja2/environment.py", line 883, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "/home/raymun/.local/share/virtualenvs/Proyectos-TA_eUHkL/lib/python3.5/site-packages/jinja2/environment.py", line 857, in _load_template
    template = self.loader.load(self, name, globals)
  File "/home/raymun/.local/share/virtualenvs/Proyectos-TA_eUHkL/lib/python3.5/site-packages/jinja2/loaders.py", line 129, in load
    code = environment.compile(source, name, filename)
  File "/home/raymun/.local/share/virtualenvs/Proyectos-TA_eUHkL/lib/python3.5/site-packages/jinja2/environment.py", line 638, in compile
    self.handle_exception(source=source_hint)
  File "/home/raymun/.local/share/virtualenvs/Proyectos-TA_eUHkL/lib/python3.5/site-packages/jinja2/environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "/home/raymun/.local/share/virtualenvs/Proyectos-TA_eUHkL/lib/python3.5/site-packages/jinja2/_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "/home/raymun/Proyectos/WebPages/projects/personal_web_page/app/templates/index.html", line 59, in template
    <p>{{ _('Collaborate with me, create teams and connect all things. Rankings, and extended premium features') }}
jinja2.exceptions.TemplateSyntaxError: expected token ',', got 'Collaborate'
2020-01-29 21:31:26,198 INFO: PREdict startup [in /home/raymun/Proyectos/WebPages/projects/personal_web_page/app/__init__.py:51]
2020-01-29 21:32:02,342 INFO: PREdict startup [in /home/raymun/Proyectos/WebPages/projects/personal_web_page/app/__init__.py:51]
2020-01-29 21:32:17,213 INFO: PREdict startup [in /home/raymun/Proyectos/WebPages/projects/personal_web_page/app/__init__.py:51]
2020-01-29 21:47:44,719 INFO: PREdict startup [in /home/raymun/Proyectos/WebPages/projects/personal_web_page/app/__init__.py:51]
2020-01-29 21:48:36,821 INFO: PREdict startup [in /home/raymun/Proyectos/WebPages/projects/personal_web_page/app/__init__.py:51]
2020-01-29 21:49:07,013 INFO: PREdict startup [in /home/raymun/Proyectos/WebPages/projects/personal_web_page/app/__init__.py:51]
2020-01-29 21:50:16,111 INFO: PREdict startup [in /home/raymun/Proyectos/WebPages/projects/personal_web_page/app/__init__.py:51]
