2020-01-28 12:51:36,135 ERROR: Exception on / [GET] [in /home/rgarcia/.local/lib/python3.6/site-packages/flask/app.py:1891]
Traceback (most recent call last):
  File "/home/rgarcia/.local/lib/python3.6/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/rgarcia/.local/lib/python3.6/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/rgarcia/.local/lib/python3.6/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/rgarcia/.local/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/rgarcia/.local/lib/python3.6/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/rgarcia/.local/lib/python3.6/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/rgarcia/Programs/web-projects/testing-site/app/routes.py", line 26, in index
    return render_template('index.html', title='Home', predictions=predictions)
  File "/home/rgarcia/.local/lib/python3.6/site-packages/flask/templating.py", line 140, in render_template
    ctx.app,
  File "/home/rgarcia/.local/lib/python3.6/site-packages/flask/templating.py", line 120, in _render
    rv = template.render(context)
  File "/home/rgarcia/.local/lib/python3.6/site-packages/jinja2/environment.py", line 1090, in render
    self.environment.handle_exception()
  File "/home/rgarcia/.local/lib/python3.6/site-packages/jinja2/environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "/home/rgarcia/.local/lib/python3.6/site-packages/jinja2/_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "/home/rgarcia/Programs/web-projects/testing-site/app/templates/index.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/home/rgarcia/Programs/web-projects/testing-site/app/templates/base.html", line 58, in top-level template code
    {% block content %}
  File "/home/rgarcia/Programs/web-projects/testing-site/app/templates/index.html", line 7, in block "content"
    {{ form.hidden_tag() }}
  File "/home/rgarcia/.local/lib/python3.6/site-packages/jinja2/environment.py", line 471, in getattr
    return getattr(obj, attribute)
jinja2.exceptions.UndefinedError: 'form' is undefined
2020-01-28 12:54:46,421 INFO: PREdict startup [in /home/rgarcia/Programs/web-projects/testing-site/app/__init__.py:46]
2020-01-28 12:59:16,257 INFO: PREdict startup [in /home/rgarcia/Programs/web-projects/testing-site/app/__init__.py:46]
2020-01-28 12:59:18,111 ERROR: Exception on / [GET] [in /home/rgarcia/.local/lib/python3.6/site-packages/flask/app.py:1891]
Traceback (most recent call last):
  File "/home/rgarcia/.local/lib/python3.6/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/rgarcia/.local/lib/python3.6/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/rgarcia/.local/lib/python3.6/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/rgarcia/.local/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/rgarcia/.local/lib/python3.6/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/rgarcia/.local/lib/python3.6/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/rgarcia/Programs/web-projects/testing-site/app/routes.py", line 26, in index
    return render_template('index.html', title='Home', predictions=predictions, user=current_user or None)
  File "/home/rgarcia/.local/lib/python3.6/site-packages/flask/templating.py", line 140, in render_template
    ctx.app,
  File "/home/rgarcia/.local/lib/python3.6/site-packages/flask/templating.py", line 120, in _render
    rv = template.render(context)
  File "/home/rgarcia/.local/lib/python3.6/site-packages/jinja2/environment.py", line 1090, in render
    self.environment.handle_exception()
  File "/home/rgarcia/.local/lib/python3.6/site-packages/jinja2/environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "/home/rgarcia/.local/lib/python3.6/site-packages/jinja2/_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "/home/rgarcia/Programs/web-projects/testing-site/app/templates/index.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/home/rgarcia/Programs/web-projects/testing-site/app/templates/base.html", line 58, in top-level template code
    {% block content %}
  File "/home/rgarcia/Programs/web-projects/testing-site/app/templates/index.html", line 8, in block "content"
    {{ form.hidden_tag() }}
  File "/home/rgarcia/.local/lib/python3.6/site-packages/jinja2/environment.py", line 471, in getattr
    return getattr(obj, attribute)
jinja2.exceptions.UndefinedError: 'form' is undefined
2020-01-28 12:59:29,655 INFO: PREdict startup [in /home/rgarcia/Programs/web-projects/testing-site/app/__init__.py:46]
2020-01-28 12:59:31,822 ERROR: Exception on / [GET] [in /home/rgarcia/.local/lib/python3.6/site-packages/flask/app.py:1891]
Traceback (most recent call last):
  File "/home/rgarcia/.local/lib/python3.6/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/rgarcia/.local/lib/python3.6/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/rgarcia/.local/lib/python3.6/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/rgarcia/.local/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/rgarcia/.local/lib/python3.6/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/rgarcia/.local/lib/python3.6/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/rgarcia/Programs/web-projects/testing-site/app/routes.py", line 26, in index
    return render_template('index.html', title='Home', predictions=predictions, user=current_user or None)
  File "/home/rgarcia/.local/lib/python3.6/site-packages/flask/templating.py", line 140, in render_template
    ctx.app,
  File "/home/rgarcia/.local/lib/python3.6/site-packages/flask/templating.py", line 120, in _render
    rv = template.render(context)
  File "/home/rgarcia/.local/lib/python3.6/site-packages/jinja2/environment.py", line 1090, in render
    self.environment.handle_exception()
  File "/home/rgarcia/.local/lib/python3.6/site-packages/jinja2/environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "/home/rgarcia/.local/lib/python3.6/site-packages/jinja2/_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "/home/rgarcia/Programs/web-projects/testing-site/app/templates/index.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/home/rgarcia/Programs/web-projects/testing-site/app/templates/base.html", line 58, in top-level template code
    {% block content %}
  File "/home/rgarcia/Programs/web-projects/testing-site/app/templates/index.html", line 8, in block "content"
    {{ form.hidden_tag() }}
  File "/home/rgarcia/.local/lib/python3.6/site-packages/jinja2/environment.py", line 471, in getattr
    return getattr(obj, attribute)
jinja2.exceptions.UndefinedError: 'form' is undefined
2020-01-28 13:00:10,303 INFO: PREdict startup [in /home/rgarcia/Programs/web-projects/testing-site/app/__init__.py:46]
