2020-01-28 13:54:28,468 INFO: PREdict startup [in /home/rgarcia/Programs/web-projects/testing-site/app/__init__.py:46]
2020-01-28 14:04:03,368 INFO: PREdict startup [in /home/rgarcia/Programs/web-projects/testing-site/app/__init__.py:46]
2020-01-28 14:04:05,675 ERROR: Exception on / [GET] [in /home/rgarcia/.local/lib/python3.6/site-packages/flask/app.py:1891]
Traceback (most recent call last):
  File "/home/rgarcia/.local/lib/python3.6/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/rgarcia/.local/lib/python3.6/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/rgarcia/.local/lib/python3.6/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/rgarcia/.local/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/rgarcia/.local/lib/python3.6/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/rgarcia/.local/lib/python3.6/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/rgarcia/Programs/web-projects/testing-site/app/routes.py", line 22, in index
    predictions = current_user.followed_predictions().paginate(page, app.config['PREDICTIONS_PER_PAGE'], False)
KeyError: 'PREDICTIONS_PER_PAGE'
2020-01-28 14:04:36,940 INFO: PREdict startup [in /home/rgarcia/Programs/web-projects/testing-site/app/__init__.py:46]
2020-01-28 14:07:09,424 INFO: PREdict startup [in /home/rgarcia/Programs/web-projects/testing-site/app/__init__.py:46]
2020-01-28 14:07:14,550 ERROR: Exception on /explore [GET] [in /home/rgarcia/.local/lib/python3.6/site-packages/flask/app.py:1891]
Traceback (most recent call last):
  File "/home/rgarcia/.local/lib/python3.6/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/rgarcia/.local/lib/python3.6/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/rgarcia/.local/lib/python3.6/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/rgarcia/.local/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/rgarcia/.local/lib/python3.6/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/rgarcia/.local/lib/python3.6/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/rgarcia/.local/lib/python3.6/site-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/home/rgarcia/Programs/web-projects/testing-site/app/routes.py", line 139, in explore
    return render_template('index.html', title='Explore', predictions=predictions)
  File "/home/rgarcia/.local/lib/python3.6/site-packages/flask/templating.py", line 140, in render_template
    ctx.app,
  File "/home/rgarcia/.local/lib/python3.6/site-packages/flask/templating.py", line 120, in _render
    rv = template.render(context)
  File "/home/rgarcia/.local/lib/python3.6/site-packages/jinja2/environment.py", line 1090, in render
    self.environment.handle_exception()
  File "/home/rgarcia/.local/lib/python3.6/site-packages/jinja2/environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "/home/rgarcia/.local/lib/python3.6/site-packages/jinja2/_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "/home/rgarcia/Programs/web-projects/testing-site/app/templates/index.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/home/rgarcia/Programs/web-projects/testing-site/app/templates/base.html", line 58, in top-level template code
    {% block content %}
  File "/home/rgarcia/Programs/web-projects/testing-site/app/templates/index.html", line 26, in block "content"
    {% for prediction in predictions %}
TypeError: 'Pagination' object is not iterable
2020-01-28 14:09:58,571 INFO: PREdict startup [in /home/rgarcia/Programs/web-projects/testing-site/app/__init__.py:46]
2020-01-28 14:19:07,321 INFO: PREdict startup [in /home/rgarcia/Programs/web-projects/testing-site/app/__init__.py:46]
2020-01-28 14:23:36,748 INFO: PREdict startup [in /home/rgarcia/Programs/web-projects/testing-site/app/__init__.py:46]
2020-01-28 14:24:24,309 INFO: PREdict startup [in /home/rgarcia/Programs/web-projects/testing-site/app/__init__.py:46]
2020-01-28 14:29:00,800 INFO: PREdict startup [in /home/rgarcia/Programs/web-projects/testing-site/app/__init__.py:46]
2020-01-28 14:29:05,661 ERROR: Exception on /user/reymon [GET] [in /home/rgarcia/.local/lib/python3.6/site-packages/flask/app.py:1891]
Traceback (most recent call last):
  File "/home/rgarcia/.local/lib/python3.6/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/rgarcia/.local/lib/python3.6/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/rgarcia/.local/lib/python3.6/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/rgarcia/.local/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/rgarcia/.local/lib/python3.6/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/rgarcia/.local/lib/python3.6/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/rgarcia/.local/lib/python3.6/site-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/home/rgarcia/Programs/web-projects/testing-site/app/routes.py", line 75, in user
    predictions = user.posts.order_by(Prediction.timestamp.desc()).paginate(
AttributeError: 'User' object has no attribute 'posts'
2020-01-28 14:29:59,303 INFO: PREdict startup [in /home/rgarcia/Programs/web-projects/testing-site/app/__init__.py:46]
2020-01-28 15:02:07,354 INFO: PREdict startup [in /home/rgarcia/Programs/web-projects/testing-site/app/__init__.py:46]
2020-01-28 15:02:34,159 INFO: PREdict startup [in /home/rgarcia/Programs/web-projects/testing-site/app/__init__.py:46]
2020-01-28 15:02:49,733 INFO: PREdict startup [in /home/rgarcia/Programs/web-projects/testing-site/app/__init__.py:46]
2020-01-28 15:09:03,140 INFO: PREdict startup [in /home/rgarcia/Programs/web-projects/testing-site/app/__init__.py:48]
2020-01-28 15:39:34,137 INFO: PREdict startup [in /home/rgarcia/Programs/web-projects/testing-site/app/__init__.py:48]
